### ISSUE TITLE
429 after i cleaned up and started from scratch

### ISSUE THREAD

**Issue by mihirv0ra** [rebane2001/matterport-dl#109]
Is there a fix for the 429? I had the download go through before just having issues when I tried to do it again :( I wish I wouldnt have deleted my downloaded model
```
python3 matterport-dl.py cdAsnVEgezF --advanced-download
Downloading base page...
Doing advanced download of dollhouse/floorplan data...
Downloading static assets...
JS FILE EXTRACTED, 217.js
JS FILE EXTRACTED, 231.js
JS FILE EXTRACTED, 27.js
JS FILE EXTRACTED, 324.js
JS FILE EXTRACTED, 325.js
JS FILE EXTRACTED, 327.js
JS FILE EXTRACTED, 378.js
JS FILE EXTRACTED, 401.js
JS FILE EXTRACTED, 425.js
JS FILE EXTRACTED, 477.js
JS FILE EXTRACTED, 625.js
JS FILE EXTRACTED, 648.js
JS FILE EXTRACTED, 653.js
JS FILE EXTRACTED, 672.js
JS FILE EXTRACTED, 679.js
JS FILE EXTRACTED, 746.js
JS FILE EXTRACTED, 782.js
JS FILE EXTRACTED, 858.js
JS FILE EXTRACTED, 948.js
JS FILE EXTRACTED, 958.js
JS FILE EXTRACTED, 973.js
Downloading model info...
Downloading images...
Downloading graph model data...
Patching graph_GetModelDetails.json URLs
Downloading model ID: cdAsnVEgezF ...
Traceback (most recent call last):
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 129, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXXX/anaconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://cdn-2.matterport.com/models/bf8552beef714fba99e49d8f7ee9216f/assets/~/d6f0db66d7204a4caa4bf06fdb61b2c4_50k.dam?t=2-5ae56a1bbd3f4d556a0c1d8a6283058fc10a52ae-1709508819-1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 690, in <module>
    initiateDownload(pageId)
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 555, in initiateDownload
    downloadPage(getPageId(url))
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 547, in downloadPage
    downloadModel(pageid, accessurl)
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 289, in downloadModel
    downloadUUID(accessurl, modeldata["job"]["uuid"])
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 48, in downloadUUID
    downloadFile(accessurl.format(
  File "/Users/XXXX/Projects/matterport-dl/matterport-dl.py", line 154, in downloadFile
    raise Exception
Exception

```

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not.
