### ISSUE TITLE
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'

### ISSUE THREAD

**Issue by Skjolbir** [rebane2001/matterport-dl#119]
```
C:\Users\MyPc\Documents\matterport-dl-main>matterport-dl.py "3EjZgu2vnFc"
Downloading capture of 3EjZgu2vnFc with base page... https://my.matterport.com/show/?m=3EjZgu2vnFc
Traceback (most recent call last):
  File "C:\Users\opera\Documents\matterport-dl-main\matterport-dl.py", line 1122, in <module>
    asyncio.run(initiateDownload(pageId))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\opera\Documents\matterport-dl-main\matterport-dl.py", line 822, in initiateDownload
    await downloadCapture(getPageId(url))
  File "C:\Users\opera\Documents\matterport-dl-main\matterport-dl.py", line 628, in downloadCapture
    file_type_content = await GetTextOnlyRequest("MAIN", True, f"https://my.matterport.com/api/player/models/{pageid}/files?type=3")  # get a valid access key, there are a few but this is a common client used one, this also makes sure it is fresh
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\opera\Documents\matterport-dl-main\matterport-dl.py", line 148, in GetTextOnlyRequest
    async with aiofiles.tempfile.NamedTemporaryFile(delete_on_close=False) as tmpFile:  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NamedTemporaryFile() got an unexpected keyword argument 'delete_on_close'
```            
           
changed:        
async with aiofiles.tempfile.NamedTemporaryFile(delete_on_close=False) as tmpFile:  # type: ignore

to:
async with aiofiles.tempfile.NamedTemporaryFile() as tmpFile:  # type: ignore        
          
and that fixed it, leading to a successful download.

**Comment by mitchcapper** [comment]
Based on this and #118 I am thinking your python version may be older.  Can you confirm your python and package versions are up to date?

**Comment by Skjolbir** [comment]
This is indeed a me issue. Python 3.11.9 on PATH.
Please close the issues, I will banish myself to the shadow realm.

**Comment by nerdoc** [comment]
ran into this as well, thanks. delete_on_close exists since Python 3.12.

**Comment by mitchcapper** [comment]
Don't worry I recently added the run.py to identify these errors for people automatically.
