### ISSUE TITLE
[Bug]: Can't find urls, try the main page. But the main page works correctly

### ISSUE THREAD

**Issue by Second24Life** [rebane2001/matterport-dl#122]
### One or more sample matterport IDs / urls that reproduce the issue

https://my.matterport.com/show/?m=7aPE8e7JXFU

### Python version

3.12.4

### Steps to reproduce

- git clone repository
- pip install -r requirements.txt
- python matterport-dl.py 7aPE8e7JXFU

### What went wrong

```
Downloading capture of 7aPE8e7JXFU with base page... https://my.matterport.com/show/?m=7aPE8e7JXFU
Traceback (most recent call last):
  File "C:\Users\User\Documents\workspace\work_project\matterport\update_downloader\matterport-dl-main\matterport-dl.py", line 1122, in <module>
    asyncio.run(initiateDownload(pageId))
  File "C:\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\workspace\work_project\matterport\update_downloader\matterport-dl-main\matterport-dl.py", line 822, in initiateDownload
    await downloadCapture(getPageId(url))
  File "C:\Users\User\Documents\workspace\work_project\matterport\update_downloader\matterport-dl-main\matterport-dl.py", line 625, in downloadCapture
    raise Exception(f"Can't find urls, try the main page: {url} in a browser to make sure it loads the model correctly")
Exception: Can't find urls, try the main page: https://my.matterport.com/show/?m=7aPE8e7JXFU in a browser to make sure it loads the model correctly
```

### Workarounds

I tried --brite-js, --no-advanced-download, --debug. Nothing useful is displayed and does not work. Always an error of not found URL

**Comment by mitchcapper** [comment]
Thanks! So it seems for some non-english pages they are now manually encoding the js with unicode escapes causing an issue. PR #124 should fix this (worked for your model) please update and try again.
