### ISSUE TITLE
[Bug]: Traceback error trying to download files

### ISSUE THREAD

**Issue by ChevyTahoe666** [rebane2001/matterport-dl#149]
### One or more sample matterport IDs / urls that reproduce the issue

YpkgPXLGFUm

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

I Don't Know, did not take the time to test it

### Started up message

C:\Python_Packages\matterport-dl-main>matterport-dl.py https://my.matterport.com/show/?m=YpkgPXLGFUm Started up a download run Running python 3.13.1 on win32

### Python version

3.13.1

### Steps to reproduce

C:\Python_Packages\matterport-dl-main>matterport-dl.py https://my.matterport.com/show/?m=YpkgPXLGFUm
Started up a download run Running python 3.13.1 on win32
Downloading capture of YpkgPXLGFUm with base page... https://my.matterport.com/show/?m=YpkgPXLGFUm
Downloading graph model data...
Doing advanced download of dollhouse/floorplan data...
Going to download tileset 3d asset models
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 37/37 [00:07<00:00,  5.22it/s]
Downloading textures and previews for tileset 3d models
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2010/2010 [00:21<00:00, 94.23it/s]
Downloading static files...
Traceback (most recent call last):
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 255, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python313\Lib\site-packages\curl_cffi\requests\models.py", line 141, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 403:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 1294, in <module>
    asyncio.run(initiateDownload(pageId))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\Brian\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 921, in initiateDownload
    await downloadCapture(getPageId(url))
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 739, in downloadCapture
    await downloadAssets(staticbase)
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 413, in downloadAssets
    showcase_cont = await downloadFileAndGetText(typeDict[file], True, base + file, file, always_download=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 222, in downloadFileAndGetText
    await downloadFile(type, shouldExist, url, file, post_data, always_download)
  File "C:\Python_Packages\matterport-dl-main\matterport-dl.py", line 278, in downloadFile
    raise Exception(f"Request error for url: {url} ({type}) that would output to: {file}") from err
Exception: Request error for url: https://static.matterport.com/showcase/24.12.3_webgl-945-g66c614cc1c/js/showcase.js (STATIC_JS) that would output to: js/showcase.js

### What went wrong

Server is responding with 403 error when trying to use matterport-dl. 

### Workarounds

The error occurred after downloading 356MB of files.  I do not understand python/web servers enough to try to debug the error.

-no-advanced-download   and  --brute-js   produced the same error.

I did try another 3d model and if failed with the a similar error.

**Comment by mitchcapper** [comment]
I am guessing it is related to #148 and the access token is expiring.  I wonder if you re-run the job again if it gest a new access token and can download some more (in theory any files it already has should be skipped over).

I will update the access token expiring within a month.

**Comment by ChevyTahoe666** [comment]
The error does not seem to be time-out related for this error. Running the command multiple times in a row results in the same error with no additional files being downloaded.

**Comment by mmarston** [comment]
I'm getting the same error and it reproduces for the sample small digital twin.

```
python .\matterport-dl.py https://my.matterport.com/show/?m=EGxFGTFyC9N
Started up a download run Running python 3.13.1 on win32
Downloading capture of EGxFGTFyC9N with base page... https://my.matterport.com/show/?m=EGxFGTFyC9N
Downloading graph model data...
Doing advanced download of dollhouse/floorplan data...
Going to download tileset 3d asset models
Downloading textures and previews for tileset 3d models
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 119/119 [00:02<00:00, 49.22it/s]
Downloading static files...
Traceback (most recent call last):
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 255, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\mjmars\AppData\Local\Programs\Python\Python313\Lib\site-packages\curl_cffi\requests\models.py", line 141, in raise_for_status
    raise RequestsError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.errors.RequestsError: HTTP Error 403:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 1294, in <module>
    asyncio.run(initiateDownload(pageId))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mjmars\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\mjmars\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\mjmars\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 921, in initiateDownload
    await downloadCapture(getPageId(url))
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 739, in downloadCapture
    await downloadAssets(staticbase)
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 413, in downloadAssets
    showcase_cont = await downloadFileAndGetText(typeDict[file], True, base + file, file, always_download=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 222, in downloadFileAndGetText
    await downloadFile(type, shouldExist, url, file, post_data, always_download)
  File "C:\temp\matterport-dl-main\matterport-dl.py", line 278, in downloadFile
    raise Exception(f"Request error for url: {url} ({type}) that would output to: {file}") from err
Exception: Request error for url: https://static.matterport.com/showcase/24.12.3_webgl-1-g8ac1598427/js/showcase.js (STATIC_JS) that would output to: js/showcase.js
```

**Comment by mmarston** [comment]
I'm able to temporarily workaround the issue by editing this line in the `downloadAssets` method:
```
    showcase_cont = await downloadFileAndGetText(typeDict[file], True, base+file, file, always_download=True)
```
And replace it with it to:
```
    showcase_url =  base + "js/showcase.694fa0133e9216d00fff.js"
    showcase_cont = await downloadFileAndGetText(typeDict[file], True, showcase_url, file, always_download=True)
```

(I got that showcase file name by looking in my browser's developer tools when a model from https://my.matterport.com/ is loaded)

**Comment by adampgeo** [comment]
I'm also getting the same error, fingers crossed for a fix

**Comment by mitchcapper** [comment]
see #150 for a potential fix.
