### ISSUE TITLE
[Bug]: Unable to complete the Download: Errors -Please help!

### ISSUE THREAD

**Issue by iwillfindthesyntaxerroreventually** [rebane2001/matterport-dl#152]
### One or more sample matterport IDs / urls that reproduce the issue

https://my.matterport.com/show/?m=EGxFGTFyC9N

### Can you reproduce this issue with the sample small digital twin https://my.matterport.com/show/?m=EGxFGTFyC9N

Yes

### Started up message

Started up a download run Running python 3.13.1 on win32 Downloading capture of EGxFGTFyC9N with base page... https://my.matterport.com/show/?m=EGxFGTFyC9N Downloading graph model data...

### Python version

3.13.1

### Steps to reproduce

Hello, sorry if I'm too new at this. I've been reading through all the forums before I posted this question:

I pasted this code: C:\Users\Username\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py "https://my.matterport.com/show/?m=EGxFGTFyC9N" --advanced-download

Clicked enter:

### What went wrong

I then get this error:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 255, in downloadFile
    response.raise_for_status()  # Raise an exception if the response has an error status code
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\curl_cffi\requests\models.py", line 146, in raise_for_status
    raise HTTPError(f"HTTP Error {self.status_code}: {self.reason}")
curl_cffi.requests.exceptions.HTTPError: HTTP Error 403:

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 1294, in <module>
    asyncio.run(initiateDownload(pageId))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 921, in initiateDownload
    await downloadCapture(getPageId(url))
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 739, in downloadCapture
    await downloadAssets(staticbase)
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 413, in downloadAssets
    showcase_cont = await downloadFileAndGetText(typeDict[file], True, base + file, file, always_download=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 222, in downloadFileAndGetText
    await downloadFile(type, shouldExist, url, file, post_data, always_download)
  File "C:\Users\User\Downloads\matterport-dl-main\matterport-dl-main\matterport-dl.py", line 278, in downloadFile
    raise Exception(f"Request error for url: {url} ({type}) that would output to: {file}") from err
Exception: Request error for url: https://static.matterport.com/showcase/24.12.3_webgl-1-g8ac1598427/js/showcase.js (STATIC_JS) that would output to: js/showcase.js

### Workarounds

_No response_

**Comment by iwillfindthesyntaxerroreventually** [comment]
If anyone has an idea, I'd super appreciate it! I'm really trying to download my home before the Matterport gets taken down. Thanks!

**Comment by mitchcapper** [comment]
Did you resolve this?  The latest master may work but feel free to email me your home ID and I can download it for you until we get the main script more bullet proof.  My email is on my GH page.

**Comment by iwillfindthesyntaxerroreventually** [comment]
Hey Mitch!!

I tried all day and couldn't get it working 😅

If it's at all possible for you to download it, I'd be super grateful.
Thanks so so much!

https://my.matterport.com/show/?m=rV67WnbyoBB&brand=0

It should say 37336 Duckling Ter

Thanks so so much!
