### ISSUE TITLE
Error downloading static assets

### ISSUE THREAD

**Issue by FredoAF** [rebane2001/matterport-dl#17]
```
Downloading static assets...
Traceback (most recent call last):
  File "/Users/<user>/Downloads/matterport-dl-main/matterport-dl.py", line 448, in <module>
    initiateDownload(pageId)
  File "/Users/<user>/Downloads/matterport-dl-main/matterport-dl.py", line 343, in initiateDownload
    downloadPage(getPageId(url))
  File "/Users/<user>/Downloads/matterport-dl-main/matterport-dl.py", line 329, in downloadPage
    patchShowcase()
  File "/Users/<user>/Downloads/matterport-dl-main/matterport-dl.py", line 208, in patchShowcase
    with open("js/showcase.js","r",encoding="UTF-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'js/showcase.js'
```

Getting the above error on a few different 3d models, eg https://my.matterport.com/show/?m=LtK9R1uoV6e

**Comment by mitchcapper** [comment]
I am not sure what version you are using.  Can you make sure you are using the latest and provide the "run_report.log" file from the model folder?

I don't have a mac but I tried these exact commands on my machine and WFM:
```
git clone https://github.com/rebane2001/matterport-dl.git
cd matterport-dl
python matterport-dl.py https://my.matterport.com/show/?m=LtK9R1uoV6e
python --version

```
with output:
```
Cloning into 'matterport-dl'...
remote: Enumerating objects: 77, done.
remote: Counting objects: 100% (77/77), done.
remote: Compressing objects: 100% (54/54), done.
Receiving objects:  61% (47/77)used 51 (delta 22), pack-reused 0
Receiving objects: 100% (77/77), 32.45 KiB | 4.06 MiB/s, done.
Resolving deltas: 100% (32/32), done.

Downloading base page...
https://cdn-1.matterport.com/models/83822fd69ca1430ca4529d78280b0c92/assets/~/{filename}?t=2-3bb98062ff4f82acc26d7ee3ac9f4423d7d06e9c-1636462324-1
Downloading static assets...
Downloading model info...
Downloading images...
Downloading graph model data...
Downloading model... access url: https://cdn-1.matterport.com/models/83822fd69ca1430ca4529d78280b0c92/assets/~/{filename}?t=2-3bb98062ff4f82acc26d7ee3ac9f4423d7d06e9c-1636462324-1
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18870/18870 [11:43<00:00, 26.82it/s]
Done!
Python 3.9.0
```

**Comment by FredoAF** [comment]
Yeah tried it on my linux desktop and it worked fine! figured python3 was python3 regardless of OS
