### ISSUE TITLE
I just get "Can't find urls".

### ISSUE THREAD

**Issue by dmd** [rebane2001/matterport-dl#89]
Am I doing something wrong here?

```
$ ./matterport-dl.py https://3dtours.aperture22.com.au/view/eremia-camel-treks/eremia-camel-museum\?platform\=captur3d.io
Downloading base page...
Traceback (most recent call last):
  File "/Users/dmd/Dropbox (Personal)/code/matterport-dl/./matterport-dl.py", line 511, in <module>
    initiateDownload(pageId)
  File "/Users/dmd/Dropbox (Personal)/code/matterport-dl/./matterport-dl.py", line 388, in initiateDownload
    downloadPage(getPageId(url))
  File "/Users/dmd/Dropbox (Personal)/code/matterport-dl/./matterport-dl.py", line 309, in downloadPage
    raise Exception("Can't find urls")
Exception: Can't find urls
```

**Comment by theo258** [comment]
On the webpage you mentioned just click on the matterport icon on the lower right corner. A new page will open where you can see the matterport ID.
https://matterport.com/discover/space/DrKffj7fnXm-> https://my.matterport.com/show/?m=DrKffj7fnXm

**Comment by mitchcapper** [comment]
This should be fixed now, please test again on master and let us know if not
